baseurl = "https://gailhantson.github.io/portfolio/"
title = "Gail Hantson"
copyright = "Copyright &copy; 2025 - Gail Hantson"
theme = "hugo-kiera"

[params]
    tagline = "Writer, Tinkerer, Technologist"